# This is a basic workflow to help you get started with Actions

name: Update README

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  #  schedule: 
  #    - cron: "0 0 * * 0"
            # - - - - -
            # | | | | |
            # | | | | +---- Day of the week (0 - 7) (Sunday is both 0 and 7)
            # | | | +------ Month (1 - 12)
            # | | +-------- Day of the month (1 - 31)
            # | +---------- Hour (0 - 23)
            # +------------ Minute (0 - 59)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-readme"
  update-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Python environment 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  
         
      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install requests

      # Run the Python script to update README.md
      - name: Update README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./src/update_readme.py -gt="$GITHUB_TOKEN"

      # Commit and push changes
      - name: Commit and push if README changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --quiet || (git add README.md && git commit -m "Updated README")
          git push
